class Constants {
  Constants._();

  static List<Map<String, String>> allLanguageList = [
  {"languageCode":"ab", "languageName":"Abkhaz", "nativeName":"аҧсуа"},
  {"languageCode":"aa", "languageName":"Afar", "nativeName":"Afaraf"},
  {"languageCode":"af", "languageName":"Afrikaans", "nativeName":"Afrikaans"},
  {"languageCode":"ak", "languageName":"Akan", "nativeName":"Akan"},
  {"languageCode":"sq", "languageName":"Albanian", "nativeName":"Shqip"},
  {"languageCode":"am", "languageName":"Amharic", "nativeName":"አማርኛ"},
  {"languageCode":"ar", "languageName":"Arabic", "nativeName":"العربية"},
  {"languageCode":"an", "languageName":"Aragonese", "nativeName":"Aragonés"},
  {"languageCode":"hy", "languageName":"Armenian", "nativeName":"Հայերեն"},
  {"languageCode":"as", "languageName":"Assamese", "nativeName":"অসমীয়া"},
  {"languageCode":"av", "languageName":"Avaric", "nativeName":"авар мацӀ, магӀарул мацӀ"},
  {"languageCode":"ae", "languageName":"Avestan", "nativeName":"avesta"},
  {"languageCode":"ay", "languageName":"Aymara", "nativeName":"aymar aru"},
  {"languageCode":"az", "languageName":"Azerbaijani", "nativeName":"azərbaycan dili"},
  {"languageCode":"bm", "languageName":"Bambara", "nativeName":"bamanankan"},
  {"languageCode":"ba", "languageName":"Bashkir", "nativeName":"башҡорт теле"},
  {"languageCode":"eu", "languageName":"Basque", "nativeName":"euskara, euskera"},
  {"languageCode":"be", "languageName":"Belarusian", "nativeName":"Беларуская"},
  {"languageCode":"bn", "languageName":"Bengali, Bangla", "nativeName":"বাংলা"},
  {"languageCode":"bh", "languageName":"Bihari", "nativeName":"भोजपुरी"},
  {"languageCode":"bi", "languageName":"Bislama", "nativeName":"Bislama"},
  {"languageCode":"bs", "languageName":"Bosnian", "nativeName":"bosanski jezik"},
  {"languageCode":"br", "languageName":"Breton", "nativeName":"brezhoneg"},
  {"languageCode":"bg", "languageName":"Bulgarian", "nativeName":"български език"},
  {"languageCode":"my", "languageName":"Burmese", "nativeName":"ဗမာစာ"},
  {"languageCode":"ca", "languageName":"Catalan; Valencian", "nativeName":"Català"},
  {"languageCode":"ch", "languageName":"Chamorro", "nativeName":"Chamoru"},
  {"languageCode":"ce", "languageName":"Chechen", "nativeName":"нохчийн мотт"},
  {"languageCode":"ny", "languageName":"Chichewa; Chewa; Nyanja", "nativeName":"chiCheŵa, chinyanja"},
  {"languageCode":"zh", "languageName":"Chinese", "nativeName":"中文 (Zhōngwén), 汉语, 漢語"},
  {"languageCode":"cv", "languageName":"Chuvash", "nativeName":"чӑваш чӗлхи"},
  {"languageCode":"kw", "languageName":"Cornish", "nativeName":"Kernewek"},
  {"languageCode":"co", "languageName":"Corsican", "nativeName":"corsu, lingua corsa"},
  {"languageCode":"cr", "languageName":"Cree", "nativeName":"ᓀᐦᐃᔭᐍᐏᐣ"},
  {"languageCode":"hr", "languageName":"Croatian", "nativeName":"hrvatski"},
  {"languageCode":"cs", "languageName":"Czech", "nativeName":"česky, čeština"},
  {"languageCode":"da", "languageName":"Danish", "nativeName":"dansk"},
  {"languageCode":"dv", "languageName":"Divehi; Dhivehi; Maldivian;", "nativeName":"ދިވެހި"},
  {"languageCode":"nl", "languageName":"Dutch", "nativeName":"Nederlands, Vlaams"},
  {"languageCode":"en", "languageName":"English", "nativeName":"English"},
  {"languageCode":"eo", "languageName":"Esperanto", "nativeName":"Esperanto"},
  {"languageCode":"et", "languageName":"Estonian", "nativeName":"eesti, eesti keel"},
  {"languageCode":"ee", "languageName":"Ewe", "nativeName":"Eʋegbe"},
  {"languageCode":"fo", "languageName":"Faroese", "nativeName":"føroyskt"},
  {"languageCode":"fj", "languageName":"Fijian", "nativeName":"vosa Vakaviti"},
  {"languageCode":"fi", "languageName":"Finnish", "nativeName":"suomi, suomen kieli"},
  {"languageCode":"fr", "languageName":"French", "nativeName":"français, langue française"},
  {"languageCode":"ff", "languageName":"Fula; Fulah; Pulaar; Pular", "nativeName":"Fulfulde, Pulaar, Pular"},
  {"languageCode":"gl", "languageName":"Galician", "nativeName":"Galego"},
  {"languageCode":"ka", "languageName":"Georgian", "nativeName":"ქართული"},
  {"languageCode":"de", "languageName":"German", "nativeName":"Deutsch"},
  {"languageCode":"el", "languageName":"Greek, Modern", "nativeName":"Ελληνικά"},
  {"languageCode":"gn", "languageName":"Guaraní", "nativeName":"Avañeẽ"},
  {"languageCode":"gu", "languageName":"Gujarati", "nativeName":"ગુજરાતી"},
  {"languageCode":"ht", "languageName":"Haitian; Haitian Creole", "nativeName":"Kreyòl ayisyen"},
  {"languageCode":"ha", "languageName":"Hausa", "nativeName":"Hausa, هَوُسَ"},
  {"languageCode":"he", "languageName":"Hebrew (modern)", "nativeName":"עברית"},
  {"languageCode":"hz", "languageName":"Herero", "nativeName":"Otjiherero"},
  {"languageCode":"hi", "languageName":"Hindi", "nativeName":"हिन्दी, हिंदी"},
  {"languageCode":"ho", "languageName":"Hiri Motu", "nativeName":"Hiri Motu"},
  {"languageCode":"hu", "languageName":"Hungarian", "nativeName":"Magyar"},
  {"languageCode":"ia", "languageName":"Interlingua", "nativeName":"Interlingua"},
  {"languageCode":"id", "languageName":"Indonesian", "nativeName":"Bahasa Indonesia"},
  {"languageCode":"ie", "languageName":"Interlingue", "nativeName":"Occidental; Interlingue"},
  {"languageCode":"ga", "languageName":"Irish", "nativeName":"Gaeilge"},
  {"languageCode":"ig", "languageName":"Igbo", "nativeName":"Asụsụ Igbo"},
  {"languageCode":"ik", "languageName":"Inupiaq", "nativeName":"Iñupiaq, Iñupiatun"},
  {"languageCode":"io", "languageName":"Ido", "nativeName":"Ido"},
  {"languageCode":"is", "languageName":"Icelandic", "nativeName":"Íslenska"},
  {"languageCode":"it", "languageName":"Italian", "nativeName":"Italiano"},
  {"languageCode":"iu", "languageName":"Inuktitut", "nativeName":"ᐃᓄᒃᑎᑐᑦ"},
  {"languageCode":"ja", "languageName":"Japanese", "nativeName":"日本語 (にほんご／にっぽんご)"},
  {"languageCode":"jv", "languageName":"Javanese", "nativeName":"basa Jawa"},
  {"languageCode":"kn", "languageName":"Kannada", "nativeName":"ಕನ್ನಡ"},
  {"languageCode":"kr", "languageName":"Kanuri", "nativeName":"Kanuri"},
  {"languageCode":"ks", "languageName":"Kashmiri", "nativeName":"कश्मीरी, كشميري‎"},
  {"languageCode":"kk", "languageName":"Kazakh", "nativeName":"Қазақ тілі"},
  {"languageCode":"km", "languageName":"Khmer", "nativeName":"ភាសាខ្មែរ"},
  {"languageCode":"ki", "languageName":"Kikuyu, Gikuyu", "nativeName":"Gĩkũyũ"},
  {"languageCode":"rw", "languageName":"Kinyarwanda", "nativeName":"Ikinyarwanda"},
  {"languageCode":"ky", "languageName":"Kirghiz, Kyrgyz", "nativeName":"кыргыз тили"},
  {"languageCode":"kv", "languageName":"Komi", "nativeName":"коми кыв"},
  {"languageCode":"kg", "languageName":"Kongo", "nativeName":"KiKongo"},
  {"languageCode":"ko", "languageName":"Korean", "nativeName":"한국어 (韓國語), 조선말 (朝鮮語)"},
  {"languageCode":"ku", "languageName":"Kurdish", "nativeName":"Kurdî, كوردی‎"},
  {"languageCode":"kj", "languageName":"Kwanyama, Kuanyama", "nativeName":"Kuanyama"},
  {"languageCode":"la", "languageName":"Latin", "nativeName":"latine, lingua latina"},
  {"languageCode":"lb", "languageName":"Luxembourgish, Letzeburgesch", "nativeName":"Lëtzebuergesch"},
  {"languageCode":"lg", "languageName":"Luganda", "nativeName":"Luganda"},
  {"languageCode":"li", "languageName":"Limburgish, Limburgan, Limburger", "nativeName":"Limburgs"},
  {"languageCode":"ln", "languageName":"Lingala", "nativeName":"Lingála"},
  {"languageCode":"lo", "languageName":"Lao", "nativeName":"ພາສາລາວ"},
  {"languageCode":"lt", "languageName":"Lithuanian", "nativeName":"lietuvių kalba"},
  {"languageCode":"lu", "languageName":"Luba-Katanga", "nativeName":""},
  {"languageCode":"lv", "languageName":"Latvian", "nativeName":"latviešu valoda"},
  {"languageCode":"gv", "languageName":"Manx", "nativeName":"Gaelg, Gailck"},
  {"languageCode":"mk", "languageName":"Macedonian", "nativeName":"македонски јазик"},
  {"languageCode":"mg", "languageName":"Malagasy", "nativeName":"Malagasy fiteny"},
  {"languageCode":"ms", "languageName":"Malay", "nativeName":"bahasa Melayu, بهاس ملايو‎"},
  {"languageCode":"ml", "languageName":"Malayalam", "nativeName":"മലയാളം"},
  {"languageCode":"mt", "languageName":"Maltese", "nativeName":"Malti"},
  {"languageCode":"mi", "languageName":"Māori", "nativeName":"te reo Māori"},
  {"languageCode":"mr", "languageName":"Marathi (Marāṭhī)", "nativeName":"मराठी"},
  {"languageCode":"mh", "languageName":"Marshallese", "nativeName":"Kajin M̧ajeļ"},
  {"languageCode":"mn", "languageName":"Mongolian", "nativeName":"монгол"},
  {"languageCode":"na", "languageName":"Nauru", "nativeName":"Ekakairũ Naoero"},
  {"languageCode":"nv", "languageName":"Navajo, Navaho", "nativeName":"Diné bizaad, Dinékʼehǰí"},
  {"languageCode":"nb", "languageName":"Norwegian Bokmål", "nativeName":"Norsk bokmål"},
  {"languageCode":"nd", "languageName":"North Ndebele", "nativeName":"isiNdebele"},
  {"languageCode":"ne", "languageName":"Nepali", "nativeName":"नेपाली"},
  {"languageCode":"ng", "languageName":"Ndonga", "nativeName":"Owambo"},
  {"languageCode":"nn", "languageName":"Norwegian Nynorsk", "nativeName":"Norsk nynorsk"},
  {"languageCode":"no", "languageName":"Norwegian", "nativeName":"Norsk"},
  {"languageCode":"ii", "languageName":"Nuosu", "nativeName":"ꆈꌠ꒿ Nuosuhxop"},
  {"languageCode":"nr", "languageName":"South Ndebele", "nativeName":"isiNdebele"},
  {"languageCode":"oc", "languageName":"Occitan", "nativeName":"Occitan"},
  {"languageCode":"oj", "languageName":"Ojibwe, Ojibwa", "nativeName":"ᐊᓂᔑᓈᐯᒧᐎᓐ"},
  {"languageCode":"om", "languageName":"Oromo", "nativeName":"Afaan Oromoo"},
  {"languageCode":"or", "languageName":"Oriya", "nativeName":"ଓଡ଼ିଆ"},
  {"languageCode":"os", "languageName":"Ossetian, Ossetic", "nativeName":"ирон æвзаг"},
  {"languageCode":"pa", "languageName":"Panjabi, Punjabi", "nativeName":"ਪੰਜਾਬੀ, پنجابی‎"},
  {"languageCode":"pi", "languageName":"Pāli", "nativeName":"पाऴि"},
  {"languageCode":"fa", "languageName":"Persian", "nativeName":"فارسی"},
  {"languageCode":"pl", "languageName":"Polish", "nativeName":"polski"},
  {"languageCode":"ps", "languageName":"Pashto, Pushto", "nativeName":"پښتو"},
  {"languageCode":"pt", "languageName":"Portuguese", "nativeName":"Português"},
  {"languageCode":"qu", "languageName":"Quechua", "nativeName":"Runa Simi, Kichwa"},
  {"languageCode":"rm", "languageName":"Romansh", "nativeName":"rumantsch grischun"},
  {"languageCode":"rn", "languageName":"Kirundi", "nativeName":"kiRundi"},
  {"languageCode":"ro", "languageName":"Romanian, Moldavian, Moldovan", "nativeName":"română"},
  {"languageCode":"ru", "languageName":"Russian", "nativeName":"русский язык"},
  {"languageCode":"sa", "languageName":"Sanskrit (Saṁskṛta)", "nativeName":"संस्कृतम्"},
  {"languageCode":"sc", "languageName":"Sardinian", "nativeName":"sardu"},
  {"languageCode":"sd", "languageName":"Sindhi", "nativeName":"सिन्धी, سنڌي، سندھی‎"},
  {"languageCode":"se", "languageName":"Northern Sami", "nativeName":"Davvisámegiella"},
  {"languageCode":"sm", "languageName":"Samoan", "nativeName":"gagana faa Samoa"},
  {"languageCode":"sg", "languageName":"Sango", "nativeName":"yângâ tî sängö"},
  {"languageCode":"sr", "languageName":"Serbian", "nativeName":"српски језик"},
  {"languageCode":"gd", "languageName":"Scottish Gaelic; Gaelic", "nativeName":"Gàidhlig"},
  {"languageCode":"sn", "languageName":"Shona", "nativeName":"chiShona"},
  {"languageCode":"si", "languageName":"Sinhala, Sinhalese", "nativeName":"සිංහල"},
  {"languageCode":"sk", "languageName":"Slovak", "nativeName":"slovenčina"},
  {"languageCode":"sl", "languageName":"Slovene", "nativeName":"slovenščina"},
  {"languageCode":"so", "languageName":"Somali", "nativeName":"Soomaaliga, af Soomaali"},
  {"languageCode":"st", "languageName":"Southern Sotho", "nativeName":"Sesotho"},
  {"languageCode":"es", "languageName":"Spanish; Castilian", "nativeName":"español, castellano"},
  {"languageCode":"su", "languageName":"Sundanese", "nativeName":"Basa Sunda"},
  {"languageCode":"sw", "languageName":"Swahili", "nativeName":"Kiswahili"},
  {"languageCode":"ss", "languageName":"Swati", "nativeName":"SiSwati"},
  {"languageCode":"sv", "languageName":"Swedish", "nativeName":"svenska"},
  {"languageCode":"ta", "languageName":"Tamil", "nativeName":"தமிழ்"},
  {"languageCode":"te", "languageName":"Telugu", "nativeName":"తెలుగు"},
  {"languageCode":"tg", "languageName":"Tajik", "nativeName":"тоҷикӣ, toğikī, تاجیکی‎"},
  {"languageCode":"th", "languageName":"Thai", "nativeName":"ไทย"},
  {"languageCode":"ti", "languageName":"Tigrinya", "nativeName":"ትግርኛ"},
  {"languageCode":"bo", "languageName":"Tibetan Standard, Tibetan, Central", "nativeName":"བོད་ཡིག"},
  {"languageCode":"tk", "languageName":"Turkmen", "nativeName":"Türkmen, Түркмен"},
  {"languageCode":"tl", "languageName":"Tagalog", "nativeName":"Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔"},
  {"languageCode":"tn", "languageName":"Tswana", "nativeName":"Setswana"},
  {"languageCode":"to", "languageName":"Tonga (Tonga Islands)", "nativeName":"faka Tonga"},
  {"languageCode":"tr", "languageName":"Turkish", "nativeName":"Türkçe"},
  {"languageCode":"ts", "languageName":"Tsonga", "nativeName":"Xitsonga"},
  {"languageCode":"tt", "languageName":"Tatar", "nativeName":"татарча, tatarça, تاتارچا‎"},
  {"languageCode":"tw", "languageName":"Twi", "nativeName":"Twi"},
  {"languageCode":"ty", "languageName":"Tahitian", "nativeName":"Reo Tahiti"},
  {"languageCode":"ug", "languageName":"Uighur, Uyghur", "nativeName":"Uyƣurqə, ئۇيغۇرچە‎"},
  {"languageCode":"uk", "languageName":"Ukrainian", "nativeName":"українська"},
  {"languageCode":"ur", "languageName":"Urdu", "nativeName":"اردو"},
  {"languageCode":"uz", "languageName":"Uzbek", "nativeName":"zbek, Ўзбек, أۇزبېك‎"},
  {"languageCode":"ve", "languageName":"Venda", "nativeName":"Tshivenḓa"},
  {"languageCode":"vi", "languageName":"Vietnamese", "nativeName":"Tiếng Việt"},
  {"languageCode":"vo", "languageName":"Volapük", "nativeName":"Volapük"},
  {"languageCode":"wa", "languageName":"Walloon", "nativeName":"Walon"},
  {"languageCode":"cy", "languageName":"Welsh", "nativeName":"Cymraeg"},
  {"languageCode":"wo", "languageName":"Wolof", "nativeName":"Wollof"},
  {"languageCode":"fy", "languageName":"Western Frisian", "nativeName":"Frysk"},
  {"languageCode":"xh", "languageName":"Xhosa", "nativeName":"isiXhosa"},
  {"languageCode":"yi", "languageName":"Yiddish", "nativeName":"ייִדיש"},
  {"languageCode":"yo", "languageName":"Yoruba", "nativeName":"Yorùbá"},
  {"languageCode":"za", "languageName":"Zhuang, Chuang", "nativeName":"Saɯ cueŋƅ, Saw cuengh"}
];
}